version: '3.9'

services:
  # catalog-api:
  #   image: ${DOCKER_REGISTRY-}catalogapi
  #   build:
  #     context: .
  #     dockerfile: Services/Catalog/Catalog.API/Dockerfile
  #   ports:
  #     - "6060:8081"
  #     - "6000:8080"
  #   environment:
  #     # - ASPNETCORE_HTTPS_PORTS=8081
  #     # - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_URLS=http://+:80
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  catalogdb:
    image: postgres:16.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/
  

volumes:
  postgres_catalog:
  