version: '3.9'

services:
# API Services    
  catalog-api:
    image: ${DOCKER_REGISTRY-}catalogapi
    depends_on: 
      - catalogdb
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "6000:8080"
      - "6060:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Kestrel__EndPoints__WebApi__Protocols=Http1
      - Kestrel__EndPoints__WebApi__Url=http://+:8080
      - ConnectionStrings__CatalogApi=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  basket-api:
    image: ${DOCKER_REGISTRY-}basketapi
    depends_on:
      - basketdb
      - distributedcache
      - discount-grpc 
    build:
       context: .
       dockerfile: Services/Basket/Basket.API/Dockerfile
    ports:
      - "6001:8080"
      - "6061:8081" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Kestrel__EndPoints__WebApi__Protocols=Http1
      - Kestrel__EndPoints__WebApi__Url=http://+:8080
      - ConnectionStrings__BasketApi=Server=basketdb;Port=5433;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379 
      - GrpcSettings__DiscountUrl=https://discount-grpc:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    
  discount-grpc:
    image: ${DOCKER_REGISTRY-}discount-grpc
    build:
        context: .
        dockerfile: Services/Discount/Discount.Grpc/Dockerfile
    ports:
       - "6002:8080"
       - "6062:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Kestrel__EndPoints__Http__Protocols=Http2
      - Kestrel__EndPoints__Http__Url=http://+:8080
      - ConnectionStrings__DiscountGrpc=Data Source=discountdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

#Redis Cache
  distributedcache:
    image: redis:7.4.0-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379" 

# Database Services
  catalogdb:
    image: postgres:16.4-alpine
    container_name: catalogdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    image: postgres:16.4-alpine
    container_name: basketdb
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    volumes:
      - postgres_basket:/var/lib/postgresql/data/

  orderdb:
    image: mcr.microsoft.com/mssql/server
    container_name: orderdb
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_USER=sa 
      - MSSQL_SA_PASSWORD=SwN12345678
    volumes:
      - sqlserver_order:/var/opt/mssql/data
    user: root
  
volumes:
  postgres_catalog:
  postgres_basket:
  sqlserver_order: