version: '3.9'

services:
# API Services    
  catalog-api:
    image: ${DOCKER_REGISTRY-}catalogapi
    depends_on: 
      - catalogdb
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "6000:8080"
      - "6060:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Kestrel__EndPoints__WebApi__Protocols=Http1
      - Kestrel__EndPoints__WebApi__Url=http://+:8080
      - ConnectionStrings__CatalogApi=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

# Database Services
  catalogdb:
    image: postgres:16.4-alpine
    container_name: catalogdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    image: postgres:16.4-alpine
    container_name: basketdb
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    volumes:
      - postgres_basket:/var/lib/postgresql/data/

volumes:
  postgres_catalog:
  postgres_basket: