name: .NET

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - '**/*'  # This ensures the workflow runs on any file changes
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore EShopMicroservices/src
    - name: Build
      run: dotnet build EShopMicroservices/src --no-restore
    - name: Test
      run: dotnet test EShopMicroservices/src --no-build --verbosity normal
