name: .NET Build

on:
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - '**/*'

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'main')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Test .NET Application
      uses: ./.github/actions/dotnet-build-test
      with:
        solution: src/eshop-microservices.sln
        dotnet_version: '8.0.x'
